# Generated by Django 4.2.6 on 2023-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_productvariant_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name_plural": "Colors"},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"verbose_name_plural": "Product Variants"},
        ),
        migrations.AlterModelOptions(
            name="quantity",
            options={"verbose_name_plural": "Quantities"},
        ),
    ]
