# Generated by Django 4.2.6 on 2023-11-04 03:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_alter_color_options_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="productvariant",
            managers=[
                ("custom_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
