# Generated by Django 4.2.6 on 2023-11-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_alter_productvariant_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="productvariant",
            managers=[],
        ),
    ]
