# Generated by Django 4.2.6 on 2023-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_alter_productvariant_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="productvariant",
        ),
        migrations.AddField(
            model_name="productimages",
            name="productvariants",
            field=models.ManyToManyField(to="adminapp.productvariant"),
        ),
    ]
