# Generated by Django 4.2.6 on 2023-11-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_alter_productvariant_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.quantity",
            ),
        ),
    ]
