# Generated by Django 4.2.6 on 2023-11-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0008_alter_productvariant_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="productvariants",
        ),
        migrations.AddField(
            model_name="productimages",
            name="productvariant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminapp.productvariant",
            ),
        ),
    ]
