# Generated by Django 4.2.6 on 2023-11-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0012_rename_product_status_cartorder_order_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartorderitems",
            unique_together={("order", "price")},
        ),
    ]
