# Generated by Django 4.2.6 on 2023-11-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0014_alter_address_options_remove_address_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
