# Generated by Django 4.2.6 on 2023-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0016_order_remove_cartorder_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
