# Generated by Django 4.2.6 on 2023-11-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0020_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.productvariant",
            ),
        ),
    ]
