# Generated by Django 4.2.6 on 2023-11-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0022_alter_orderitem_product_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.productvariant",
            ),
        ),
    ]
