# Generated by Django 4.2.6 on 2023-11-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0024_remove_orderitem_product_variant_orderitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitems",
            name="image",
        ),
        migrations.RemoveField(
            model_name="cartorderitems",
            name="product_title",
        ),
    ]
