# Generated by Django 4.2.6 on 2023-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0030_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
