# Generated by Django 4.2.6 on 2023-11-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0031_alter_orderitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
