# Generated by Django 4.2.6 on 2023-11-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0032_remove_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
