# Generated by Django 4.2.6 on 2023-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0034_address_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
