# Generated by Django 4.2.6 on 2023-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0035_product_is_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
