# Generated by Django 4.2.6 on 2023-11-17 07:15

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0036_alter_orderitem_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="co",
                        unique=True,
                    ),
                ),
                ("hashed_code", models.CharField(editable=False, max_length=64)),
                ("discount_percentage", models.PositiveIntegerField()),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
