# Generated by Django 4.2.6 on 2023-11-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0037_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="hashed_code",
            field=models.CharField(max_length=64),
        ),
    ]
