# Generated by Django 4.2.6 on 2023-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0039_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_done",
            field=models.BooleanField(default=False),
        ),
    ]
