# Generated by Django 4.2.6 on 2023-11-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0040_order_payment_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_done",
        ),
    ]
