# Generated by Django 4.2.6 on 2023-11-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0042_orderitem_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminapp.productvariant",
            ),
        ),
    ]
