# Generated by Django 4.2.6 on 2023-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0043_wishlist_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_done",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
