# Generated by Django 4.2.6 on 2023-11-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0046_offers_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="variants",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="adminapp.productvariant",
            ),
        ),
    ]
