# Generated by Django 4.2.6 on 2023-11-28 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0047_alter_offers_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="offers",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="offers",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="offers",
            name="valid_to",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
