# Generated by Django 4.2.6 on 2023-12-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0052_referral_created_referral_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="variants",
        ),
    ]
