# Generated by Django 4.2.6 on 2023-12-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminapp", "0056_alter_referral_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referrer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
