# Generated by Django 4.2.6 on 2023-12-02 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0059_blogs_remove_productreview_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_images",
                    models.ImageField(
                        default="images/backgrounds/default_image.jpeg",
                        upload_to="product-images",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="adminapp.blogs",
                    ),
                ),
            ],
        ),
    ]
