# Generated by Django 4.2.6 on 2023-12-02 04:37

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0060_blogadditionalimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogadditionalimage",
            name="add_images",
            field=models.ImageField(
                blank=True,
                default="images\x08ackgrounds\\Face.jpeg",
                null=True,
                upload_to=adminapp.models.user_directory_path,
            ),
        ),
    ]
