# Generated by Django 4.2.6 on 2023-12-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0062_contactus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUs",
        ),
    ]
