# Generated by Django 4.2.6 on 2023-12-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0063_delete_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="50.00", max_digits=10, null=True
            ),
        ),
    ]
