# Generated by Django 4.2.6 on 2023-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0064_alter_productvariant_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogadditionalimage",
            name="add_images",
            field=models.ImageField(upload_to="additional_blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
