# Generated by Django 4.2.6 on 2023-12-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0066_alter_blogadditionalimage_add_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review",
                to="adminapp.productvariant",
            ),
        ),
    ]
