# Generated by Django 4.2.7 on 2023-12-04 04:43

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0070_alter_blogadditionalimage_add_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogadditionalimage",
            name="add_images",
            field=models.ImageField(
                blank=True,
                default="images\x08ackgrounds\\Face.jpeg",
                null=True,
                upload_to=adminapp.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(
                default="images\x08ackgrounds\\Face.jpeg",
                upload_to=adminapp.models.user_directory_path,
            ),
        ),
    ]
