# Generated by Django 4.2.7 on 2023-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0073_alter_blogadditionalimage_add_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogadditionalimage",
            name="add_images",
            field=models.ImageField(blank=True, null=True, upload_to="product-images"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product-images"),
        ),
    ]
