# Generated by Django 4.2.7 on 2023-12-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0075_alter_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offers",
            name="Brand",
        ),
    ]
