# Generated by Django 4.2.7 on 2023-12-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0077_returnedproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnedproduct",
            name="product_name",
        ),
        migrations.AddField(
            model_name="returnedproduct",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.order",
            ),
        ),
    ]
