# Generated by Django 4.2.7 on 2023-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0078_remove_returnedproduct_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnedproduct",
            name="reason_for_return",
            field=models.CharField(max_length=255),
        ),
    ]
