# Generated by Django 4.2.7 on 2023-12-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0082_alter_returnedproduct_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnedproduct",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="returned",
                to="adminapp.orderitem",
            ),
        ),
    ]
