# Generated by Django 4.2.7 on 2023-12-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0083_alter_returnedproduct_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="offers",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="50.00", max_digits=10, null=True
            ),
        ),
    ]
