# Generated by Django 4.2.7 on 2023-12-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0085_alter_productvariant_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.color",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.quantity",
            ),
        ),
    ]
