# Generated by Django 4.2.7 on 2023-12-15 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminapp", "0088_coupon_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
