# Generated by Django 4.2.7 on 2023-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0090_alter_coupon_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="unit",
            field=models.CharField(blank=True, default="g", max_length=50, null=True),
        ),
    ]
