# Generated by Django 4.2.7 on 2023-12-22 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0092_alter_quantity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
