# Generated by Django 4.2.7 on 2023-12-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0093_productvariant_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="offers",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.productvariant",
            ),
        ),
    ]
