# Generated by Django 4.2.7 on 2023-12-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0095_remove_offers_variant_remove_productvariant_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offers",
            name="price",
        ),
    ]
